# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9a93481a7b9629e44b3cca91c9edeebd8e1a419ffb3167d2ff0c8d55f25bfae73b2791c2699d1f1d00415104858fe5b4683eed03fedd41e4f12241c19974808c

test:
  secret_key_base: 6e2ca7ed6090db15ae802e1825046825b4cf4cb7828932c6e51868641c5f9c8d9c0e95bd544bd6e3dda969504896f42114d6c432953f2ec6205c232e36f85a85

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
